### ISSUE TITLE
Any way the icons can be updated?

### ISSUE THREAD

**Issue by samaguilar** [dstaley/react-native-bootstrap-icons#2]
Is there a way to update the version of Bootstrap Icons being used? Currently it looks like its using v1.1

**Comment by dstaley** [comment]
Updated! Grab the latest version with `npm i react-native-bootstrap-icons@1.5.0`.

**Comment by samaguilar** [comment]
@dstaley Hi! Not to bother again, but could you update to the latest bootstrap-icons version?

Also; is there a way I can update the icons myself? How could I go about doing that? Thank you!
